canvi del títol
reactjs/ca.reactjs.org pull request #76
Opened 2020-08-30 07:57 UTC by nglvnyls

iniciant un draft

2020-08-30 18:08 UTC, nglvnyls commented
hola, 
No he sabut traduir "Skiplinks" o "Skip Navigation Links" i ho he deixat tal qual. S'accepten suggerències

2020-09-03 15:39 UTC, pepjo requested changes
Hi ha alguns canvis menors. Crec que estaria bé informar de l’dioma del enllaç si aquest és diferent del català tal i com ja has fet en alguns d’ells.

2020-09-03 15:39 UTC, pepjo commented on content/docs/accessibility.md
> +També pots fer servir el mòdul [react-axe](https://github.com/dylanb/react-axe) per a informar d'aquests resultats d'accessibilitat directament a la consola mentre  desenvolupes i depures.
Eliminar segon espais entre "mentre" i "desenvolupes" ?

2020-09-03 15:39 UTC, pepjo commented on content/docs/accessibility.md
> +[Create React App](https://github.com/facebookincubator/create-react-app) té activat aquest connector amb un subconjunt de regles. Si voleu habilitar encara més regles d'accessibilitat podeu crear un
Eliminar l'espai entre . i eslintrc

2020-09-03 15:39 UTC, pepjo commented on content/docs/accessibility.md
> +El complement [eslint-plugin-jsx-a11y](https://github.com/evcohen/eslint-plugin-jsx-a11y) per ESLint proporciona informació de retorn "AST linting"  sobre els problemes d'accessibilitat en el teu JSX
Eliminar doble espai després de "AST listing"

2020-09-03 15:39 UTC, pepjo commented on content/docs/accessibility.md
> +Podem comprovar algunes funcions d'accessibilitat directament en el nostre codi JSX. Sovint, els controls intel·ligents per als rols , estats i propietats de l'ARIA ja ens són proporcionats en IDE's
Eliminar espai entre rols i ,

2020-09-03 15:39 UTC, pepjo commented on content/docs/accessibility.md
> +1. Fes servir l' `Enter` per activar elements.
Eliminar espai entre apòstrof i `Enter`

2020-09-03 15:39 UTC, pepjo commented on content/docs/accessibility.md
> +Quan s'utilitza un HOC per ampliar components, es recomana [reenviar la referència](/docs/forwarding-refs.html) al component envoltat fent servir la funció `forwardRef` de React. Si un HOC d'un terce
Eliminar espai entre ref i ,

2020-09-03 15:39 UTC, pepjo commented on content/docs/accessibility.md
> +De vegades un component pare ha d'establir el focus a un element d'un component fill. Podem fer-ho [posant les referències DOM als components pare ](/docs/refs-and-the-dom.html#exposing-dom-refs-to-p
Eliminar espai entre pare i ]

2020-09-04 13:46 UTC, nglvnyls commented
tots els canvis fets

2020-09-06 18:42 UTC, seraco commented on content/docs/accessibility.md
> +L'accessibilitat del contingut web (també coneguda com  [**a11y**](https://en.wiktionary.org/wiki/a11y)) és el disseny i la creació de continguts web que tothom pot utilitzar. El suport a l'accessibi
Em sembla bona idea @pepjo.

2020-09-11 19:36 UTC, pepjo approved these changes

2020-09-11 19:37 UTC, merged