fin als final
reactjs/ca.reactjs.org pull request #86
Opened 2020-09-21 20:34 UTC by nglvnyls

Traducció de la pàgina sencera

2020-10-04 17:43 UTC, seraco commented on content/docs/reference-events.md
> +Als teus gestors d'esdeveniments se li passaran instàncies de `SyntheticEvent`, un contenidor compatible amb diversos navegadors que conté l'esdeveniment natiu del navegador. Té la mateixa interfície
```suggestion
Als teus gestors d'esdeveniments se li passaran instàncies de `SyntheticEvent`, un contenidor compatible amb diversos navegadors que conté l'esdeveniment natiu del navegador. Té la mateixa interfície que l'esdeveniment natiu del navegador, incloent `stopPropagation()` i `preventDefault()`, excepte que els esdeveniments funcionen de forma idèntica a tots els navegadors.
```

2020-10-04 17:51 UTC, seraco commented on content/docs/reference-events.md
> +Si creus que necessites l'esdeveniment natiu del navegador per alguna raó, només cal que facis servir l'atribut `nativeEvent` per obtenir-lo. Els esdeveniments sintètics són diferents dels esdevenime
```suggestion
Si creus que necessites l'esdeveniment natiu del navegador per alguna raó, només cal que facis servir l'atribut `nativeEvent` per obtenir-lo. Els esdeveniments sintètics són diferents dels esdeveniments natius del navegador i no es corresponen directament. Per exemple a `onMouseLeave` `event.nativeEvent` apuntarà a un esdeveniment `mouseout`. La relació específic no és part de l'API pública i pot canviar en qualsevol moment. Cada objecte `SyntheticEvent` té els següents atributs:
```

2020-10-04 17:52 UTC, seraco commented on content/docs/reference-events.md
> +> A partir de la v0.14, el retorn de `false` d'un gestor d'esdeveniments ja no atura la propagació d'esdeveniments. Per tant, `e.stopPropagation()` o `e.preventionDefault()` s'han d'activar manualmen
```suggestion
> A partir de la v0.14, retornar `false` des d'un gestor d'esdeveniments ja no atura la propagació d'esdeveniments. Per tant, `e.stopPropagation()` o `e.preventionDefault()` s'han d'activar manualment, segons correspongui.
```

2020-10-04 17:55 UTC, seraco commented on content/docs/reference-events.md
> +  // Segueixes poden exportar les propietats de l'esdeveniment.
```suggestion
  // Encara pots exportar les propietats de l'esdeveniment.
```

2020-10-04 17:57 UTC, seraco commented on content/docs/reference-events.md
> +React normalitza els esdeveniments per que les seves propietats siguin coherents entre els diferents tipus de navegadors.
```suggestion
React normalitza els esdeveniments perquè les seves propietats siguin coherents entre els diferents tipus de navegadors.
```

2020-10-04 17:59 UTC, seraco commented on content/docs/reference-events.md
> +- [Esdeveniments de formulari](#form-events)
```suggestion
- [Esdeveniments de Formulari](#form-events)
```

2020-10-04 18:01 UTC, seraco commented on content/docs/reference-events.md
> +- [Esdeveniments de Media](#media-events)
```suggestion
- [Esdeveniments de Multimèdia](#media-events)
```

2020-10-04 18:01 UTC, seraco commented on content/docs/reference-events.md
> +## Referencia {#reference}
```suggestion
## Referència {#reference}
```

2020-10-04 18:04 UTC, seraco commented on content/docs/reference-events.md
> +Els esdeveniments `onMouseEnter` i `onMouseLeave` es propaguen des de l'element que es deixa fins a l'element al qual s'entra en lloc de fer la propagació normal i no tenen fase de captura.
```suggestion
Els esdeveniments `onMouseEnter` i `onMouseLeave` es propaguen des de l'element que es deixa a l'element al qual s'entra en lloc de fer la propagació normal i no tenen fase de captura.
```

2020-10-04 18:07 UTC, seraco commented on content/docs/reference-events.md
> +Els esdeveniments `onPointerIntro` i `onPointerLeave` es propaguen des de l'element que es deixa fins a l'element al qual s'entra en lloc de fer la propagació normal i no tenen una fase de captura.
```suggestion
Els esdeveniments `onPointerEnter` i `onPointerLeave` es propaguen des de l'element que es deixa fins a l'element al qual s'entra en lloc de fer la propagació normal i no tenen una fase de captura. 
```

2020-10-04 18:10 UTC, seraco commented on content/docs/reference-events.md
> +Una nota sobre la compatibilitat amb els diversos navegador:
```suggestion
Una nota sobre la compatibilitat amb els diversos navegadors:
```

2020-10-04 18:12 UTC, seraco commented on content/docs/reference-events.md
> +Si la vostra aplicació requereix esdeveniments de punter, recomanem afegir un *polyfill* d'esdeveniments d'un altre proveïdors.
```suggestion
Si la vostra aplicació requereix esdeveniments de punter, recomanem afegir un *polyfill* d'esdeveniments d'un altre proveïdor.
```

2020-10-04 18:12 UTC, seraco commented on content/docs/reference-events.md
> +### Esdeveniments tàctils {#touch-events}
```suggestion
### Esdeveniments Tàctils {#touch-events}
```

2020-10-04 18:13 UTC, seraco commented on content/docs/reference-events.md
> +### Esdeveniments de Media {#media-events}
```suggestion
### Esdeveniments de Multimèdia {#media-events}
```

2020-10-04 18:14 UTC, seraco requested changes
There are a few things that should be changed before merge.

2020-10-04 18:15 UTC, seraco commented
@nglvnyls, thanks very much for the contribution. 😋

2020-10-04 20:48 UTC, nglvnyls commented
It's my pleasure. Thank to you @seraco for yours great reviews.

2021-06-26 14:01 UTC, seraco approved these changes

2021-06-26 14:01 UTC, merged